baseURL = "https://blog.lineleader.io/"
languageCode = "en-us"
theme="line-leader"
title = "LineLeader - Better Disney though planning"

disqusShortname = "lineleader-blog"
copyright = "Copyright LineLeader All Rights Reserved"

[author]
    name = "Chris Marshall"

paginate = 5 # Number of posts to show before paginating
